export function accessAdminPage(): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>ERS Brain · Access & Roles</title>
  <style>
    :root{color-scheme:light;--ink:#17211b;--muted:#667069;--line:#d9ded9;--paper:#fbfcfa;--panel:#fff;--green:#1e6a46;--amber:#926400;--red:#a32929;--blue:#275d9b}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{padding:20px 28px;border-bottom:1px solid var(--line);background:var(--panel);display:flex;justify-content:space-between;align-items:center;gap:16px}h1{font-size:20px;margin:0}header p{margin:2px 0 0;color:var(--muted)}main{max-width:1440px;margin:auto;padding:24px 28px 48px}.toolbar,.card{background:var(--panel);border:1px solid var(--line);border-radius:10px}.toolbar{padding:14px 16px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}.card{margin-top:18px;padding:18px}h2{font-size:16px;margin:0 0 12px}button,select,input,textarea{font:inherit}button{border:1px solid #bfc8c1;border-radius:7px;background:#fff;padding:7px 11px;cursor:pointer}button.primary,.primary-link{background:var(--green);border:1px solid var(--green);border-radius:7px;color:#fff;padding:7px 11px;text-decoration:none}button.danger{color:var(--red)}button:disabled{opacity:.5;cursor:not-allowed}input,select,textarea{border:1px solid #bdc7c0;border-radius:7px;padding:8px;background:#fff}input[type=search]{min-width:300px}.muted{color:var(--muted)}.status{margin-left:auto}.ok{color:var(--green)}.warn{color:var(--amber)}.fail{color:var(--red)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px 8px;border-top:1px solid var(--line);vertical-align:top}th{font-size:12px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted)}code{font-size:12px}.pill{display:inline-block;padding:2px 7px;border-radius:999px;background:#edf2ee}.drift-none{color:var(--green)}.drift-multiple,.drift-mismatch,.drift-unexpected,.drift-missing{color:var(--red)}dialog{width:min(580px,calc(100% - 32px));border:1px solid var(--line);border-radius:10px;padding:0}dialog::backdrop{background:#17211b66}.dialog-body{padding:20px}.dialog-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.fields label{display:flex;flex-direction:column;gap:4px}.fields .wide{grid-column:1/-1}.results{margin:10px 0 0;padding:0;list-style:none}.results button{width:100%;text-align:left;margin-top:6px}.error{padding:10px;border-left:3px solid var(--red);background:#fff3f3}.hidden{display:none}@media(max-width:760px){header,main{padding-left:16px;padding-right:16px}.status{width:100%;margin-left:0}.fields{grid-template-columns:1fr}input[type=search]{min-width:0;width:100%}.table-wrap{overflow:auto}}
  </style>
</head>
<body>
<header><div><h1>ERS Brain · Access & Roles</h1><p>Hosted owner control plane · deployment-bound to ers-brain</p></div><button id="signout" class="hidden">End admin session</button></header>
<main>
  <section class="toolbar"><strong id="identity">Checking admin session…</strong><span id="expiry" class="muted"></span><span id="status" class="status muted">Loading</span><a id="signin" class="hidden primary-link" href="/admin/login">Sign in with Microsoft</a></section>
  <div id="error" class="card error hidden" role="alert"></div>
  <section id="controls" class="hidden">
    <div class="card"><h2>Add or change access</h2><p class="muted">Search the ERS directory, then confirm exactly one managed role. Reader is the default.</p><div><input id="search" type="search" placeholder="Name or ERS email" autocomplete="off"><button id="searchBtn">Search directory</button></div><ul id="results" class="results"></ul></div>
    <div class="card"><div style="display:flex;justify-content:space-between;gap:12px"><div><h2>Effective grants</h2><p class="muted">Local enforcement compared with the four live managed Entra groups.</p></div><button id="refresh">Refresh</button></div><div class="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Graph</th><th>Updated</th><th></th></tr></thead><tbody id="grants"></tbody></table></div></div>
    <div class="card"><h2>Audit history</h2><div class="table-wrap"><table><thead><tr><th>When</th><th>Actor</th><th>Target</th><th>Change</th><th>Graph</th><th>Reason</th></tr></thead><tbody id="audit"></tbody></table></div></div>
  </section>
</main>
<dialog id="changeDialog"><div class="dialog-body"><h2>Confirm access change</h2><p id="targetLabel"></p><div class="fields"><label>Role<select id="role"><option value="reader">Reader</option><option value="member">Curator</option><option value="admin">Admin</option><option value="owner">Owner</option></select></label><label>Status<select id="grantStatus"><option value="active">Active</option><option value="suspended">Suspended</option><option value="revoked">Revoked</option></select></label><label class="wide">Reason<textarea id="reason" rows="2" maxlength="500">Owner-confirmed access change</textarea></label></div><p class="muted">This changes both the local Brain grant and fixed Entra managed-group membership. Revocation and downgrade take effect locally first.</p><div class="dialog-actions"><button id="cancel">Cancel</button><button id="confirm" class="primary">Confirm change</button></div></div></dialog>
<script>
let csrf="",selected=null;
const $=id=>document.getElementById(id);
function showError(message){$("error").textContent=message;$("error").classList.remove("hidden")}
function clearError(){$("error").classList.add("hidden");$("error").textContent=""}
async function api(path,options={}){const headers={...(options.headers||{})};if(options.body){headers["content-type"]="application/json";headers["x-brain-csrf"]=csrf}const response=await fetch(path,{...options,headers});const data=await response.json().catch(()=>({error:"Unexpected server response"}));if(!response.ok)throw new Error(data.error||"Request failed");return data}
function td(text){const cell=document.createElement("td");cell.textContent=text==null?"—":String(text);return cell}
function roleLabel(role){return role==="member"?"Curator":role.charAt(0).toUpperCase()+role.slice(1)}
function openChange(target,grant){selected=target;$("targetLabel").textContent=target.displayName||target.name||target.mail||target.email||target.id;$("role").value=grant?.role||"reader";$("grantStatus").value=grant?.status||"active";$("changeDialog").showModal()}
async function load(){clearError();const session=await api("/admin/api/session").catch(error=>({authenticated:false,error:error.message}));if(!session.authenticated){$("identity").textContent="Owner sign-in required";$("status").textContent="No active admin session";$("signin").classList.remove("hidden");return}csrf=session.csrfToken;$("identity").textContent=session.name||session.login||session.objectId;$("expiry").textContent="Session expires "+new Date(session.expiresAt*1000).toLocaleTimeString();$("status").textContent="Owner session active";$("status").className="status ok";$("controls").classList.remove("hidden");$("signout").classList.remove("hidden");await refresh()}
async function refresh(){clearError();$("status").textContent="Refreshing…";try{const data=await api("/admin/api/access");const body=$("grants");body.replaceChildren();for(const grant of data.grants){const row=document.createElement("tr");row.append(td(grant.name||grant.email||grant.providerUserId),td(roleLabel(grant.role)),td(grant.status),td(grant.graphRoles.length?grant.graphRoles.map(roleLabel).join(", ")+" · "+grant.drift:grant.drift),td(grant.updatedAt?new Date(grant.updatedAt).toLocaleString():"—"));row.children[3].className="drift-"+grant.drift;const action=td("");const button=document.createElement("button");button.textContent=grant.drift==="none"?"Change":"Reconcile";button.onclick=()=>openChange({id:grant.providerUserId,displayName:grant.name,mail:grant.email,userPrincipalName:grant.email},grant);action.replaceChildren(button);row.append(action);body.append(row)}const audit=$("audit");audit.replaceChildren();for(const event of data.audit){const row=document.createElement("tr");row.append(td(new Date(event.createdAt).toLocaleString()),td(event.actorUserId),td(event.targetName||event.targetUserId),td(event.action+" · "+(event.oldRole||"—")+" → "+(event.newRole||"—")+" · "+(event.newStatus||"—")),td(event.graphOutcome||"—"),td(event.reason||"—"));audit.append(row)}$("status").textContent="Current";$("status").className="status ok"}catch(error){showError(error.message);$("status").textContent="Needs attention";$("status").className="status fail"}}
$("searchBtn").onclick=async()=>{clearError();try{const data=await api("/admin/api/users?q="+encodeURIComponent($("search").value));const list=$("results");list.replaceChildren();for(const user of data.users){const item=document.createElement("li");const button=document.createElement("button");button.textContent=(user.displayName||user.userPrincipalName||user.id)+(user.mail?" · "+user.mail:"");button.onclick=()=>openChange(user,null);item.append(button);list.append(item)}}catch(error){showError(error.message)}};
$("refresh").onclick=refresh;$("cancel").onclick=()=>$("changeDialog").close();
$("confirm").onclick=async()=>{if(!selected)return;$("confirm").disabled=true;clearError();try{await api("/admin/api/access",{method:"POST",body:JSON.stringify({target:selected,role:$("role").value,status:$("grantStatus").value,reason:$("reason").value,confirmed:true})});$("changeDialog").close();await refresh()}catch(error){showError(error.message)}finally{$("confirm").disabled=false}};
$("signout").onclick=async()=>{await api("/admin/api/logout",{method:"POST",body:"{}"}).catch(()=>{});location.reload()};
load().catch(error=>showError(error.message));
</script>
</body></html>`;
}
