export const monitoringPage = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Brain status</title><link rel="stylesheet" href="/monitor/style.css"><script src="/monitor/app.js" defer></script></head><body><main>
<header><div><p class="eyebrow">BRAIN MONITORING</p><h1>Brain status</h1><p class="muted">Service health and observed sync activity.</p></div><button id="theme" type="button" aria-label="Switch colour theme">Theme</button></header>
<section id="access" class="card"><h2 id="access-title">Checking your session…</h2><p id="access-message">Sign in with the account you use for this Brain.</p><a class="button" href="/monitor/login">Sign in</a></section>
<div id="dashboard" hidden><div class="toolbar"><div><h2 id="brain"></h2><p class="muted" id="role"></p></div><button id="refresh" type="button">Refresh</button><form action="/monitor/logout" method="post"><button type="submit">Sign out</button></form></div>
<p class="muted" id="observed" aria-live="polite"></p><div class="grid"><section class="card"><p class="eyebrow">HOSTED SERVICE</p><h2 id="service">Checking…</h2><p id="version"></p><p id="attention"></p></section><section class="card"><p class="eyebrow">SYNC OBSERVATION</p><h2 id="sync"></h2><p id="sync-time"></p><p class="muted">Activity from the configured sync operator. This does not check every colleague’s device.</p></section></div>
<section class="card"><h2>Local inboxes stay local</h2><p>This page cannot inspect your local inbox. You can still open and manage it manually, using your existing filesystem access.</p></section>
<section class="card" id="diagnostics" hidden><h2>Operational diagnostics</h2><p id="window" class="muted"></p><dl><dt>Measured operations</dt><dd id="operations"></dd><dt>Failed operations</dt><dd id="failed"></dd><dt>95th percentile response</dt><dd id="latency"></dd><dt>Authentication events</dt><dd id="auth"></dd><dt>Open sync conflicts</dt><dd id="conflicts"></dd></dl><p class="muted">Server handling time excludes client and network overhead. Resolve conflicts through the reviewed Brain workflow.</p></section></div>
<footer>Read-only monitoring · Access follows your current Brain role.</footer></main></body></html>`;

export const monitoringCss = `:root{color-scheme:light dark;--bg:#f4f6f5;--card:#fff;--text:#19332c;--muted:#52675f;--border:#c8d5cf;--accent:#176c50}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.55 system-ui,sans-serif}main{max-width:980px;margin:auto;padding:40px 24px}header,.toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}header{margin-bottom:30px}h1{font-size:38px;letter-spacing:-1px;margin:0}h2{font-size:22px;margin:4px 0 12px}p{margin:8px 0}.eyebrow{font-size:12px;font-weight:750;letter-spacing:1.4px}.muted,footer{color:var(--muted)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card{background:var(--card);border:1px solid var(--border);border-radius:14px;padding:24px;margin:18px 0;overflow-wrap:anywhere}.grid .card{margin-bottom:0}.toolbar{margin-top:24px}.toolbar>div{flex:1}button,.button{display:inline-block;font:inherit;padding:9px 16px;border-radius:8px;border:1px solid var(--accent);background:var(--card);color:var(--accent);text-decoration:none;cursor:pointer}button:focus-visible,a:focus-visible{outline:3px solid var(--accent);outline-offset:3px}form{margin:0}dl{display:grid;grid-template-columns:1fr auto;gap:12px}dd{margin:0;font-weight:700}footer{font-size:13px;margin-top:28px}[hidden]{display:none!important}html[data-theme=dark]{--bg:#12221c;--card:#1b3027;--text:#e7f2ec;--muted:#b7ccc1;--border:#3b5749;--accent:#8bddb5}@media(prefers-color-scheme:dark){html:not([data-theme=light]){--bg:#12221c;--card:#1b3027;--text:#e7f2ec;--muted:#b7ccc1;--border:#3b5749;--accent:#8bddb5}}@media(max-width:620px){main{padding:24px 16px}.grid{grid-template-columns:1fr;gap:0}h1{font-size:30px}.card{padding:20px}.toolbar>div{flex-basis:100%}}`;

export const monitoringJs = `const el=id=>document.getElementById(id);const text=(id,value)=>el(id).textContent=value;
let loading=false;async function load(){if(loading)return;loading=true;el('refresh').disabled=true;el('diagnostics').hidden=true;text('service','Checking…');text('attention','');text('sync','Checking…');text('sync-time','');text('observed','Refreshing observations…');try{const response=await fetch('/monitor/api/status'+location.search,{cache:'no-store',signal:AbortSignal.timeout(10000)});if(response.status===401||response.status===403){el('dashboard').hidden=true;el('access').hidden=false;text('access-title',response.status===401?'Sign in to see Brain status':'This account has no current access');text('access-message','Use the account authorized for this Brain.');return;}if(!response.ok)throw new Error();const data=await response.json();el('access').hidden=true;el('dashboard').hidden=false;text('brain',data.brain_id);text('role','Your role: '+data.role);text('service','Available');text('version','Deployed v'+data.server_version);text('observed','Observed '+new Date(data.observed_at).toLocaleString());text('attention',data.attention_required?'A sync conflict needs operator review.':'No open sync conflict reported.');text('sync',data.sync.state==='recent'?'Recent activity':data.sync.state==='stale'?'Observation is stale':'Not observed');text('sync-time',data.sync.observed_at?new Date(data.sync.observed_at).toLocaleString():'No heartbeat available.');if(data.diagnostics){const d=data.diagnostics;el('diagnostics').hidden=false;text('window',d.window);text('operations',d.operations);text('failed',d.failed_operations);text('latency',d.p95_ms===null?'Not measured':d.p95_ms+' ms');text('auth',d.auth_events);text('conflicts',d.open_conflicts);}}catch{el('dashboard').hidden=true;el('access').hidden=false;text('access-title','Status is unavailable');text('access-message','Current health could not be verified. Refresh this page to try again.');}finally{loading=false;el('refresh').disabled=false;}}
el('refresh').onclick=load;el('theme').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark'||(!document.documentElement.dataset.theme&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=dark?'light':'dark';};load();setInterval(()=>{if(!document.hidden)load();},60000);`;
